id: hl7.fhir.dk.kl.gateway.care
canonical: http://gateway.kl.dk/1.0
name: KLGateway
status: active
version: "1.0.1"
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: Build CI
publisher:
  name: KL
  url: http://www.kl.dk
jurisdiction: urn:iso:std:iso:3166#DK "Denmark"
	
dependencies:
  dk.fhir.ig.dk-core: current
  dk.fhir.ig.kl.common.caresocial: current

menu:
  Home: index.html
  Artifacts: artifacts.html
  Homecare Example: Homecare.html
  Nursing Example: Nursing.html
  Downloads: downloads.html

parameters:
  apply-contact: true
  apply-juristiction: true
  apply-publisher: true