id: kl.dk.fhir.gateway
canonical: http://fhir.kl.dk/gateway
name: KLGateway
status: active # draft # active
version: "1.2.0"
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: release # CI Build # release
publisher:
  name: KL
  url: http://www.kl.dk
jurisdiction: urn:iso:std:iso:3166#DK "Denmark"
	
dependencies:
  hl7.fhir.dk.core: 3.2.0
  kl.dk.fhir.term: 2.1.0

menu:
  Home: index.html
  Artifacts: artifacts.html
  Homecare Example: Homecare.html
  Nursing Example: Nursing.html
  Downloads: downloads.html

parameters:
  apply-contact: true
  apply-publisher: true
#  apply-juristiction: true
